export enum ActionType {
  CREATE_USER = "CREATE_USER",
  CREATE_BRACKET = "CREATE_BRACKET",
  DECLARE_MATCH_WINNER = "DECLARE_MATCH_WINNER",
  LOG_IN = "LOG_IN",
  LOG_OUT = "LOG_OUT",
  REFRESH_TOKEN = "REFRESH_TOKEN",
  LOAD_USER = "LOAD_USER",
}
